//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jet
{
    using System;
    using System.Collections.Generic;
    
    public partial class JetOrderLine
    {
        public string JetOrderLineId { get; set; }
        public string JetOrderId { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
